# Terminal capabilities
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",xterm-ghostty:RGB"
set -s extended-keys on

# General behaviour
set -g mouse on
set -g focus-events on
set -sg escape-time 10
set -g history-limit 100000

# Window and pane numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Vim-like copy mode
setw -g mode-keys vi
set -s set-clipboard on

# Status bar
set -g status on
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100

# Prevent applications from renaming windows
set -g allow-rename off
