# Hyprdots theme settings

# Dynamic / Matugen
MATUGEN_MODE="auto"
MATUGEN_LIGHT_THRESHOLD="0.56"
MATUGEN_SCHEME="scheme-content"
MATUGEN_PREFER="saturation"

# Hybrid
HYBRID_ACCENT_TINT="0.25"
HYBRID_NEUTRAL_TINT="0.12"
