#!/usr/bin/env zsh

emulate -L zsh
setopt ERR_EXIT NO_UNSET PIPE_FAIL

typeset root output output_dir temporary source_file source_label theme_file
typeset -a theme_files module_files source_files

root="${0:A:h}"

output="${STARSHIP_OUTPUT:-$root/starship.toml}"
theme_file="${STARSHIP_THEME_FILE:-}"

output_dir="${output:A:h}"

module_files=("$root"/modules/*.toml(N))

if ((${#module_files} == 0)); then
  print -u2 -- "No Starship modules found"
  exit 1
fi

source_files=(
  "$root/prompt.toml"
)

if [[ -n "$theme_file" ]]; then
  if [[ ! -r "$theme_file" ]]; then
    print -u2 -- "Cannot read Starship theme: $theme_file"
    exit 1
  fi

  source_files+=("$theme_file")
else
  theme_files=("$root"/themes/*.toml(N))

  if ((${#theme_files} == 0)); then
    print -u2 -- "No Starship themes found"
    exit 1
  fi

  source_files+=(
    "$root/current.toml"
    "${theme_files[@]}"
  )
fi

source_files+=(
  "${module_files[@]}"
)

if ((! $+commands[starship])); then
  print -u2 -- "Starship is not installed"
  exit 127
fi

command mkdir -p -- "$output_dir"

temporary="$(mktemp "$output_dir/.starship.toml.XXXXXX")"

cleanup_starship_build() {
  if [[ -n "${temporary:-}" && -e "$temporary" ]]; then
    command rm -f -- "$temporary"
  fi
}

trap cleanup_starship_build EXIT HUP INT TERM

{
  print -r -- "# Generated by build.zsh — do not edit directly."

  for source_file in "${source_files[@]}"; do
    if [[ ! -r "$source_file" ]]; then
      print -u2 -- "Cannot read: $source_file"
      exit 1
    fi

    print
    source_label="${source_file#$root/}"

    if [[ "$source_label" == "$source_file" ]]; then
      source_label="${source_file:t}"
    fi

    print -r -- "# Source: $source_label"
    command cat -- "$source_file"
  done
} >"$temporary"

if ! STARSHIP_CONFIG="$temporary" \
  command starship print-config >/dev/null; then
  print -u2 -- "Starship configuration validation failed"
  exit 1
fi

command chmod 0644 "$temporary"
command mv -f -- "$temporary" "$output"
temporary=""

print -r -- "Built: $output"
