#!/usr/bin/env zsh

emulate -L zsh
setopt ERR_EXIT NO_UNSET PIPE_FAIL

typeset root output temporary source_file
typeset -a theme_files module_files

root="${0:A:h}"
output="$root/starship.toml"

theme_files=("$root"/themes/*.toml(N))
module_files=("$root"/modules/*.toml(N))

if (( ${#theme_files} == 0 )); then
    print -u2 -- "No Starship themes found"
    exit 1
fi

if (( ${#module_files} == 0 )); then
    print -u2 -- "No Starship modules found"
    exit 1
fi

if (( ! $+commands[starship] )); then
    print -u2 -- "Starship is not installed"
    exit 127
fi

temporary="$(mktemp "$root/.starship.toml.XXXXXX")"

cleanup_starship_build() {
    if [[ -n "${temporary:-}" && -e "$temporary" ]]; then
        command rm -f -- "$temporary"
    fi
}

trap cleanup_starship_build EXIT HUP INT TERM

{
    print -r -- "# Generated by build.zsh — do not edit directly."

    for source_file in \
        "$root/prompt.toml" \
        "$root/current.toml" \
        "${theme_files[@]}" \
        "${module_files[@]}"
    do
        if [[ ! -r "$source_file" ]]; then
            print -u2 -- "Cannot read: $source_file"
            exit 1
        fi

        print
        print -r -- "# Source: ${source_file#$root/}"
        command cat -- "$source_file"
    done
} > "$temporary"

if ! STARSHIP_CONFIG="$temporary" \
    command starship print-config >/dev/null
then
    print -u2 -- "Starship configuration validation failed"
    exit 1
fi

command chmod 0644 "$temporary"
command mv -f -- "$temporary" "$output"
temporary=""

print -r -- "Built: $output"
