# 3 min
listener {
    timeout = 180

    on-timeout = brightness.sh 70 800
    on-resume = brightness.sh max 400
}

# 5 min
listener {
    timeout = 300

    on-timeout = brightness.sh 45 700; loginctl lock-session
}

# 10 min
listener {
    timeout = 600

    on-timeout = brightness.sh 20 900
}

# 15 min
listener {
    timeout = 900

    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 1 hour
listener {
    timeout = 3600

    on-timeout = poweroff.sh
}
