general {
    lock_cmd = lock.sh
    before_sleep_cmd = lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on && brightness.sh restore

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false

    inhibit_sleep = 3
}


# 3 min → 70%
listener {
    timeout = 180

    on-timeout = brightness.sh 70
    on-resume = brightness.sh restore
}


# 5 min → 45% + Hyprlock
listener {
    timeout = 300

    on-timeout = brightness.sh 45 && lock.sh
}


# 10 min → 20%
listener {
    timeout = 600

    on-timeout = brightness.sh 20
}


# 15 min → display off
listener {
    timeout = 900

    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightness.sh restore
}


# 1 hour → graceful shutdown
listener {
    timeout = 3600

    on-timeout = poweroff.sh
}
