# ─────────────────────────────────────────────
# Catppuccin
# ─────────────────────────────────────────────

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Match the background of the old configuration
set -g @catppuccin_status_background "#24273a"


# ─────────────────────────────────────────────
# Status line
# ─────────────────────────────────────────────

set -g status-left ""
set -g status-right ""

# Left
set -g status-left "#{E:@catppuccin_status_application}"
set -ag status-left "#{E:@catppuccin_status_uptime}"

# Right
set -g status-right \
    "#[bg=#{@thm_flamingo},fg=#{@thm_crust}]#[reverse]#[noreverse]󱀙  "

set -ag status-right \
    "#[fg=#{@thm_fg},bg=#24273a] #I "

set -ag status-right \
    "#{E:@catppuccin_status_session}"

# Hide regular window list
set -g window-status-format ""
set -g window-status-current-format ""
