#!/usr/bin/env python3

import math
import os
import re
import sys
from pathlib import Path

if len(sys.argv) != 4:
    raise SystemExit(
        "usage: blend-palette.py <dynamic.theme> <static.theme> <output.theme>"
    )

dynamic_file = Path(sys.argv[1])
static_file = Path(sys.argv[2])
output_file = Path(sys.argv[3])

accent_weight = float(os.environ.get("HYPRDOTS_HYBRID_ACCENT_TINT", "0.25"))
neutral_weight = float(os.environ.get("HYPRDOTS_HYBRID_NEUTRAL_TINT", "0.12"))

if not 0.0 <= accent_weight <= 1.0:
    raise SystemExit("HYPRDOTS_HYBRID_ACCENT_TINT must be between 0 and 1")

if not 0.0 <= neutral_weight <= 1.0:
    raise SystemExit("HYPRDOTS_HYBRID_NEUTRAL_TINT must be between 0 and 1")


assignment = re.compile(
    r'^\s*((?:COLOR|ANSI)_[A-Z0-9_]+)\s*=\s*["\']?(#[0-9a-fA-F]{6})["\']?\s*$'
)


def read_palette(path):
    order = []
    colors = {}

    for line in path.read_text().splitlines():
        match = assignment.match(line)

        if not match:
            continue

        name, color = match.groups()
        order.append(name)
        colors[name] = color.lower()

    return order, colors


def srgb_to_linear(value):
    if value <= 0.04045:
        return value / 12.92

    return ((value + 0.055) / 1.055) ** 2.4


def linear_to_srgb(value):
    if value <= 0.0031308:
        return 12.92 * value

    return 1.055 * (value ** (1.0 / 2.4)) - 0.055


def hex_to_oklab(color):
    r = int(color[1:3], 16) / 255.0
    g = int(color[3:5], 16) / 255.0
    b = int(color[5:7], 16) / 255.0

    r = srgb_to_linear(r)
    g = srgb_to_linear(g)
    b = srgb_to_linear(b)

    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b

    l_ = math.copysign(abs(l) ** (1.0 / 3.0), l)
    m_ = math.copysign(abs(m) ** (1.0 / 3.0), m)
    s_ = math.copysign(abs(s) ** (1.0 / 3.0), s)

    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


def oklab_to_hex(lab):
    lightness, a, b = lab

    l_ = lightness + 0.3963377774 * a + 0.2158037573 * b
    m_ = lightness - 0.1055613458 * a - 0.0638541728 * b
    s_ = lightness - 0.0894841775 * a - 1.2914855480 * b

    l = l_ ** 3
    m = m_ ** 3
    s = s_ ** 3

    r = +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    b = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s

    channels = []

    for value in (r, g, b):
        value = linear_to_srgb(value)
        value = max(0.0, min(1.0, value))
        channels.append(round(value * 255))

    return "#{:02x}{:02x}{:02x}".format(*channels)


neutral_roles = {
    "COLOR_TEXT",
    "COLOR_SUBTEXT1",
    "COLOR_SUBTEXT0",
    "COLOR_OVERLAY2",
    "COLOR_OVERLAY1",
    "COLOR_OVERLAY0",
    "COLOR_SURFACE2",
    "COLOR_SURFACE1",
    "COLOR_SURFACE0",
    "COLOR_BASE",
    "COLOR_MANTLE",
    "COLOR_CRUST",
    "ANSI_BLACK",
    "ANSI_WHITE",
    "ANSI_BRIGHT_BLACK",
    "ANSI_BRIGHT_WHITE",
}


dynamic_order, dynamic = read_palette(dynamic_file)
_, static = read_palette(static_file)

if not dynamic_order:
    raise SystemExit(f"No colors found in {dynamic_file}")

missing = [name for name in dynamic_order if name not in static]

if missing:
    raise SystemExit(
        "Static theme is missing colors: " + ", ".join(missing)
    )

output = [
    "# Generated by Hyprdots Hybrid theme.",
    f"# Dynamic palette: {dynamic_file}",
    f"# Tint palette: {static_file}",
    f"# Accent tint: {accent_weight:.2f}",
    f"# Neutral tint: {neutral_weight:.2f}",
    "",
]

for name in dynamic_order:
    dynamic_lab = hex_to_oklab(dynamic[name])
    static_lab = hex_to_oklab(static[name])

    weight = neutral_weight if name in neutral_roles else accent_weight

    # Keep Dynamic lightness exactly as-is.
    # Only shift chroma/hue toward the selected static theme.
    hybrid = (
        dynamic_lab[0],
        dynamic_lab[1] * (1.0 - weight) + static_lab[1] * weight,
        dynamic_lab[2] * (1.0 - weight) + static_lab[2] * weight,
    )

    output.append(f'{name}="{oklab_to_hex(hybrid)}"')

output_file.parent.mkdir(parents=True, exist_ok=True)
output_file.write_text("\n".join(output) + "\n")
