#!/usr/bin/env bash

if [[ -n "${HYPRDOTS_THEME_RENDER_LOADED:-}" ]]; then
  return 0
fi

readonly HYPRDOTS_THEME_RENDER_LOADED=1

# shellcheck source=common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/common.sh"

render_rasi_palette() {
  local output="$1"

  cat >"$output" <<EOF_RASI
/* Generated by Hyprdots theme manager. */
* {
    rosewater: $COLOR_ROSEWATER;
    flamingo:  $COLOR_FLAMINGO;
    pink:      $COLOR_PINK;
    mauve:     $COLOR_MAUVE;
    red:       $COLOR_RED;
    maroon:    $COLOR_MAROON;
    peach:     $COLOR_PEACH;
    yellow:    $COLOR_YELLOW;
    green:     $COLOR_GREEN;
    teal:      $COLOR_TEAL;
    sky:       $COLOR_SKY;
    sapphire:  $COLOR_SAPPHIRE;
    blue:      $COLOR_BLUE;
    lavender:  $COLOR_LAVENDER;

    text:      $COLOR_TEXT;
    subtext1:  $COLOR_SUBTEXT1;
    subtext0:  $COLOR_SUBTEXT0;

    overlay2:  $COLOR_OVERLAY2;
    overlay1:  $COLOR_OVERLAY1;
    overlay0:  $COLOR_OVERLAY0;

    surface2:  $COLOR_SURFACE2;
    surface1:  $COLOR_SURFACE1;
    surface0:  $COLOR_SURFACE0;

    base:      $COLOR_BASE;
    mantle:    $COLOR_MANTLE;
    crust:     $COLOR_CRUST;
}
EOF_RASI
}

render_waybar_palette() {
  local output="$1"

  cat >"$output" <<EOF_CSS
/* Generated by Hyprdots theme manager. */
@define-color rosewater $COLOR_ROSEWATER;
@define-color flamingo $COLOR_FLAMINGO;
@define-color pink $COLOR_PINK;
@define-color mauve $COLOR_MAUVE;
@define-color red $COLOR_RED;
@define-color maroon $COLOR_MAROON;
@define-color peach $COLOR_PEACH;
@define-color yellow $COLOR_YELLOW;
@define-color green $COLOR_GREEN;
@define-color teal $COLOR_TEAL;
@define-color sky $COLOR_SKY;
@define-color sapphire $COLOR_SAPPHIRE;
@define-color blue $COLOR_BLUE;
@define-color lavender $COLOR_LAVENDER;

@define-color text $COLOR_TEXT;
@define-color subtext1 $COLOR_SUBTEXT1;
@define-color subtext0 $COLOR_SUBTEXT0;

@define-color overlay2 $COLOR_OVERLAY2;
@define-color overlay1 $COLOR_OVERLAY1;
@define-color overlay0 $COLOR_OVERLAY0;

@define-color surface2 $COLOR_SURFACE2;
@define-color surface1 $COLOR_SURFACE1;
@define-color surface0 $COLOR_SURFACE0;

@define-color base $COLOR_BASE;
@define-color mantle $COLOR_MANTLE;
@define-color crust $COLOR_CRUST;

@define-color bar_bg transparent;
@define-color module_bg @surface0;
@define-color module_fg @text;
@define-color module_hover @surface1;
@define-color accent @mauve;
@define-color accent_fg @crust;
@define-color muted @overlay0;
@define-color warning @yellow;
@define-color critical @red;
EOF_CSS
}

render_swaync_palette() {
  local output="$1"
  local base_rgb
  local surface0_rgb

  base_rgb="$(theme_rgb_csv "$COLOR_BASE")"
  surface0_rgb="$(theme_rgb_csv "$COLOR_SURFACE0")"

  cat >"$output" <<EOF_CSS
/* Generated by Hyprdots theme manager. */
:root {
    --rosewater: $COLOR_ROSEWATER;
    --flamingo: $COLOR_FLAMINGO;
    --pink: $COLOR_PINK;
    --mauve: $COLOR_MAUVE;
    --red: $COLOR_RED;
    --maroon: $COLOR_MAROON;
    --peach: $COLOR_PEACH;
    --yellow: $COLOR_YELLOW;
    --green: $COLOR_GREEN;
    --teal: $COLOR_TEAL;
    --sky: $COLOR_SKY;
    --sapphire: $COLOR_SAPPHIRE;
    --blue: $COLOR_BLUE;
    --lavender: $COLOR_LAVENDER;

    --text: $COLOR_TEXT;
    --subtext1: $COLOR_SUBTEXT1;
    --subtext0: $COLOR_SUBTEXT0;

    --overlay2: $COLOR_OVERLAY2;
    --overlay1: $COLOR_OVERLAY1;
    --overlay0: $COLOR_OVERLAY0;

    --surface2: $COLOR_SURFACE2;
    --surface1: $COLOR_SURFACE1;
    --surface0: $COLOR_SURFACE0;

    --base: $COLOR_BASE;
    --mantle: $COLOR_MANTLE;
    --crust: $COLOR_CRUST;

    --cc-bg: rgba($base_rgb, 0.88);
    --noti-bg: $surface0_rgb;
    --noti-bg-alpha: 0.92;
    --floating-noti-bg-alpha: 0.82;
    --noti-bg-darker: var(--mantle);
    --noti-bg-hover: var(--surface1);
    --noti-bg-focus: var(--surface1);
    --noti-border-color: var(--surface1);
    --noti-close-bg: var(--surface1);
    --noti-close-bg-hover: var(--red);
    --text-color: var(--text);
    --text-color-disabled: var(--overlay0);
    --bg-selected: var(--mauve);
    --accent: var(--mauve);
    --accent-text: var(--crust);
    --critical: var(--red);

    --border-radius: 12px;
    --notification-icon-size: 48px;
    --notification-app-icon-size: 20px;
    --notification-group-icon-size: 28px;
    --font-size-body: 14px;
    --font-size-summary: 15px;
}
EOF_CSS
}

render_wlogout_palette() {
  local output="$1"
  local crust_rgb
  local surface0_rgb
  local surface1_rgb

  crust_rgb="$(theme_rgb_csv "$COLOR_CRUST")"
  surface0_rgb="$(theme_rgb_csv "$COLOR_SURFACE0")"
  surface1_rgb="$(theme_rgb_csv "$COLOR_SURFACE1")"

  cat >"$output" <<EOF_CSS
/* Generated by Hyprdots theme manager. */
@define-color rosewater $COLOR_ROSEWATER;
@define-color flamingo $COLOR_FLAMINGO;
@define-color pink $COLOR_PINK;
@define-color mauve $COLOR_MAUVE;
@define-color red $COLOR_RED;
@define-color maroon $COLOR_MAROON;
@define-color peach $COLOR_PEACH;
@define-color yellow $COLOR_YELLOW;
@define-color green $COLOR_GREEN;
@define-color teal $COLOR_TEAL;
@define-color sky $COLOR_SKY;
@define-color sapphire $COLOR_SAPPHIRE;
@define-color blue $COLOR_BLUE;
@define-color lavender $COLOR_LAVENDER;
@define-color text $COLOR_TEXT;
@define-color subtext1 $COLOR_SUBTEXT1;
@define-color overlay2 $COLOR_OVERLAY2;
@define-color surface2 $COLOR_SURFACE2;
@define-color surface1 $COLOR_SURFACE1;
@define-color surface0 $COLOR_SURFACE0;
@define-color base $COLOR_BASE;
@define-color mantle $COLOR_MANTLE;
@define-color crust $COLOR_CRUST;

@define-color logout_overlay rgba($crust_rgb, 0.72);
@define-color logout_button rgba($surface0_rgb, 0.60);
@define-color logout_button_hover rgba($surface1_rgb, 0.82);
EOF_CSS
}

render_hyprlock_palette() {
  local output="$1"
  local crust_rgb
  local surface2_rgb
  local text_rgb

  crust_rgb="$(theme_rgb_csv "$COLOR_CRUST")"
  surface2_rgb="$(theme_rgb_csv "$COLOR_SURFACE2")"
  text_rgb="$(theme_rgb_csv "$COLOR_TEXT")"
  cat >"$output" <<EOF_HYPR
# Generated by Hyprdots theme manager.
\$rosewater = rgb($(theme_hex "$COLOR_ROSEWATER"))
\$flamingo = rgb($(theme_hex "$COLOR_FLAMINGO"))
\$pink = rgb($(theme_hex "$COLOR_PINK"))
\$mauve = rgb($(theme_hex "$COLOR_MAUVE"))
\$red = rgb($(theme_hex "$COLOR_RED"))
\$maroon = rgb($(theme_hex "$COLOR_MAROON"))
\$peach = rgb($(theme_hex "$COLOR_PEACH"))
\$yellow = rgb($(theme_hex "$COLOR_YELLOW"))
\$green = rgb($(theme_hex "$COLOR_GREEN"))
\$teal = rgb($(theme_hex "$COLOR_TEAL"))
\$sky = rgb($(theme_hex "$COLOR_SKY"))
\$sapphire = rgb($(theme_hex "$COLOR_SAPPHIRE"))
\$blue = rgb($(theme_hex "$COLOR_BLUE"))
\$lavender = rgb($(theme_hex "$COLOR_LAVENDER"))

\$text = rgb($(theme_hex "$COLOR_TEXT"))
\$subtext1 = rgb($(theme_hex "$COLOR_SUBTEXT1"))
\$subtext0 = rgb($(theme_hex "$COLOR_SUBTEXT0"))
\$overlay2 = rgb($(theme_hex "$COLOR_OVERLAY2"))
\$overlay1 = rgb($(theme_hex "$COLOR_OVERLAY1"))
\$overlay0 = rgb($(theme_hex "$COLOR_OVERLAY0"))
\$surface2 = rgb($(theme_hex "$COLOR_SURFACE2"))
\$surface1 = rgb($(theme_hex "$COLOR_SURFACE1"))
\$surface0 = rgb($(theme_hex "$COLOR_SURFACE0"))
\$base = rgb($(theme_hex "$COLOR_BASE"))
\$mantle = rgb($(theme_hex "$COLOR_MANTLE"))
\$crust = rgb($(theme_hex "$COLOR_CRUST"))

\$lock_text = \$text
\$lock_subtext = \$subtext1
\$lock_input_bg = rgba($crust_rgb, 0.45)
\$lock_input_fg = \$text
\$lock_input_border = rgba($surface2_rgb, 0.65)
\$lock_check = \$blue
\$lock_fail = \$red
\$lock_caps = \$yellow
\$lock_layout = rgba($text_rgb,0.95)
\$lock_shadow = rgba(0,0,0,0.75)
EOF_HYPR
}

render_hyprland_palette() {
  local output="$1"

  cat >"$output" <<EOF_LUA
-- Generated by Hyprdots theme manager.
-- This file is intentionally not loaded automatically yet.
return {
  name = "$THEME_NAME",
  display_name = "$THEME_DISPLAY_NAME",

  rosewater = "$COLOR_ROSEWATER",
  flamingo = "$COLOR_FLAMINGO",
  pink = "$COLOR_PINK",
  mauve = "$COLOR_MAUVE",
  red = "$COLOR_RED",
  maroon = "$COLOR_MAROON",
  peach = "$COLOR_PEACH",
  yellow = "$COLOR_YELLOW",
  green = "$COLOR_GREEN",
  teal = "$COLOR_TEAL",
  sky = "$COLOR_SKY",
  sapphire = "$COLOR_SAPPHIRE",
  blue = "$COLOR_BLUE",
  lavender = "$COLOR_LAVENDER",

  text = "$COLOR_TEXT",
  subtext1 = "$COLOR_SUBTEXT1",
  subtext0 = "$COLOR_SUBTEXT0",
  overlay2 = "$COLOR_OVERLAY2",
  overlay1 = "$COLOR_OVERLAY1",
  overlay0 = "$COLOR_OVERLAY0",
  surface2 = "$COLOR_SURFACE2",
  surface1 = "$COLOR_SURFACE1",
  surface0 = "$COLOR_SURFACE0",
  base = "$COLOR_BASE",
  mantle = "$COLOR_MANTLE",
  crust = "$COLOR_CRUST",
}
EOF_LUA
}

render_ghostty_palette() {
  local output="$1"

  cat >"$output" <<EOF_GHOSTTY
# Generated by Hyprdots theme manager.
background = $(theme_hex "$COLOR_BASE")
foreground = $(theme_hex "$COLOR_TEXT")
cursor-color = $(theme_hex "$COLOR_ROSEWATER")
cursor-text = $(theme_hex "$COLOR_BASE")
selection-background = $(theme_hex "$COLOR_SURFACE2")
selection-foreground = $(theme_hex "$COLOR_TEXT")

palette = 0=$(theme_hex "$ANSI_BLACK")
palette = 1=$(theme_hex "$ANSI_RED")
palette = 2=$(theme_hex "$ANSI_GREEN")
palette = 3=$(theme_hex "$ANSI_YELLOW")
palette = 4=$(theme_hex "$ANSI_BLUE")
palette = 5=$(theme_hex "$ANSI_MAGENTA")
palette = 6=$(theme_hex "$ANSI_CYAN")
palette = 7=$(theme_hex "$ANSI_WHITE")
palette = 8=$(theme_hex "$ANSI_BRIGHT_BLACK")
palette = 9=$(theme_hex "$ANSI_BRIGHT_RED")
palette = 10=$(theme_hex "$ANSI_BRIGHT_GREEN")
palette = 11=$(theme_hex "$ANSI_BRIGHT_YELLOW")
palette = 12=$(theme_hex "$ANSI_BRIGHT_BLUE")
palette = 13=$(theme_hex "$ANSI_BRIGHT_MAGENTA")
palette = 14=$(theme_hex "$ANSI_BRIGHT_CYAN")
palette = 15=$(theme_hex "$ANSI_BRIGHT_WHITE")
EOF_GHOSTTY
}

render_starship_palette() {
  local output="$1"

  cat >"$output" <<EOF_TOML
# Generated by Hyprdots theme manager.
palette = "current"

[palettes.current]
rosewater = "$COLOR_ROSEWATER"
flamingo = "$COLOR_FLAMINGO"
pink = "$COLOR_PINK"
mauve = "$COLOR_MAUVE"
red = "$COLOR_RED"
maroon = "$COLOR_MAROON"
peach = "$COLOR_PEACH"
yellow = "$COLOR_YELLOW"
green = "$COLOR_GREEN"
teal = "$COLOR_TEAL"
sky = "$COLOR_SKY"
sapphire = "$COLOR_SAPPHIRE"
blue = "$COLOR_BLUE"
lavender = "$COLOR_LAVENDER"
text = "$COLOR_TEXT"
subtext1 = "$COLOR_SUBTEXT1"
subtext0 = "$COLOR_SUBTEXT0"
overlay2 = "$COLOR_OVERLAY2"
overlay1 = "$COLOR_OVERLAY1"
overlay0 = "$COLOR_OVERLAY0"
surface2 = "$COLOR_SURFACE2"
surface1 = "$COLOR_SURFACE1"
surface0 = "$COLOR_SURFACE0"
base = "$COLOR_BASE"
mantle = "$COLOR_MANTLE"
crust = "$COLOR_CRUST"
EOF_TOML
}

render_btop_palette() {
  local output="$1"

  cat >"$output" <<EOF_BTOP
# Generated by Hyprdots theme manager.
theme[main_bg]="$COLOR_BASE"
theme[main_fg]="$COLOR_TEXT"
theme[title]="$COLOR_TEXT"
theme[hi_fg]="$COLOR_BLUE"
theme[selected_bg]="$COLOR_SURFACE1"
theme[selected_fg]="$COLOR_BLUE"
theme[inactive_fg]="$COLOR_OVERLAY1"
theme[graph_text]="$COLOR_ROSEWATER"
theme[meter_bg]="$COLOR_SURFACE1"
theme[proc_misc]="$COLOR_ROSEWATER"
theme[cpu_box]="$COLOR_MAUVE"
theme[mem_box]="$COLOR_GREEN"
theme[net_box]="$COLOR_MAROON"
theme[proc_box]="$COLOR_BLUE"
theme[div_line]="$COLOR_OVERLAY0"
theme[temp_start]="$COLOR_GREEN"
theme[temp_mid]="$COLOR_YELLOW"
theme[temp_end]="$COLOR_RED"
theme[cpu_start]="$COLOR_TEAL"
theme[cpu_mid]="$COLOR_SAPPHIRE"
theme[cpu_end]="$COLOR_LAVENDER"
theme[free_start]="$COLOR_MAUVE"
theme[free_mid]="$COLOR_LAVENDER"
theme[free_end]="$COLOR_BLUE"
theme[cached_start]="$COLOR_SAPPHIRE"
theme[cached_mid]="$COLOR_BLUE"
theme[cached_end]="$COLOR_LAVENDER"
theme[available_start]="$COLOR_PEACH"
theme[available_mid]="$COLOR_MAROON"
theme[available_end]="$COLOR_RED"
theme[used_start]="$COLOR_GREEN"
theme[used_mid]="$COLOR_TEAL"
theme[used_end]="$COLOR_SKY"
theme[download_start]="$COLOR_PEACH"
theme[download_mid]="$COLOR_MAROON"
theme[download_end]="$COLOR_RED"
theme[upload_start]="$COLOR_GREEN"
theme[upload_mid]="$COLOR_TEAL"
theme[upload_end]="$COLOR_SKY"
theme[process_start]="$COLOR_SAPPHIRE"
theme[process_mid]="$COLOR_LAVENDER"
theme[process_end]="$COLOR_MAUVE"
EOF_BTOP
}

render_rmpc_palette() {
  local output="$1"

  cat >"$output" <<EOF_RON
#![enable(implicit_some)]
#![enable(unwrap_newtypes)]
#![enable(unwrap_variant_newtypes)]

// Generated by Hyprdots theme manager.
(
    background_color: "$COLOR_BASE",
    text_color: "$COLOR_TEXT",
    header_background_color: None,
    modal_background_color: "$COLOR_MANTLE",
    preview_label_style: ( fg: "$COLOR_MAUVE", ),
    preview_metadata_group_style: ( fg: "$COLOR_MAUVE", modifiers: "Bold", ),
    tab_bar: (
        enabled: true,
        active_style: ( fg: "$COLOR_BASE", bg: "$COLOR_BLUE", modifiers: "Bold", ),
        inactive_style: ( fg: "$COLOR_SUBTEXT0", ),
    ),
    highlighted_item_style: ( fg: "$COLOR_PINK", modifiers: "Bold", ),
    current_item_style: ( fg: "$COLOR_BASE", bg: "$COLOR_BLUE", modifiers: "Bold", ),
    borders_style: ( fg: "$COLOR_OVERLAY0", ),
    highlight_border_style: ( fg: "$COLOR_BLUE", ),
    progress_bar: (
        symbols: ["━", "━", "●"],
        track_style: ( fg: "$COLOR_SURFACE0", ),
        elapsed_style: ( fg: "$COLOR_BLUE", ),
        thumb_style: ( fg: "$COLOR_MAUVE", bg: "$COLOR_SURFACE0", ),
    ),
    scrollbar: (
        symbols: ["│", "█", "▲", "▼"],
        track_style: ( fg: "$COLOR_SURFACE0", ),
        ends_style: ( fg: "$COLOR_OVERLAY0", ),
        thumb_style: ( fg: "$COLOR_BLUE", ),
    ),
)
EOF_RON
}

render_yazi_flavor() {
  local output_dir="$1"

  mkdir -p -- "$output_dir"

  cat >"$output_dir/flavor.toml" <<EOF_TOML
#:schema https://yazi-rs.github.io/schemas/theme.json

# Generated by Hyprdots theme manager.

[app]
overall = { bg = "$COLOR_BASE" }

[mgr]
cwd = { fg = "$COLOR_BLUE" }

find_keyword = { fg = "$COLOR_YELLOW", bold = true, italic = true, underline = true }
find_position = { fg = "$COLOR_MAUVE", bg = "reset", bold = true, italic = true }

symlink_target = { fg = "$COLOR_TEAL", italic = true }

marker_copied = { fg = "$COLOR_GREEN", bg = "$COLOR_GREEN" }
marker_cut = { fg = "$COLOR_RED", bg = "$COLOR_RED" }
marker_marked = { fg = "$COLOR_TEAL", bg = "$COLOR_TEAL" }
marker_selected = { fg = "$COLOR_YELLOW", bg = "$COLOR_YELLOW" }

count_copied = { fg = "$COLOR_BASE", bg = "$COLOR_GREEN" }
count_cut = { fg = "$COLOR_BASE", bg = "$COLOR_RED" }
count_selected = { fg = "$COLOR_BASE", bg = "$COLOR_YELLOW" }

border_style = { fg = "$COLOR_SURFACE2" }

[tabs]
active = { fg = "$COLOR_BASE", bg = "$COLOR_BLUE", bold = true }
inactive = { fg = "$COLOR_SUBTEXT0", bg = "$COLOR_SURFACE0" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "$COLOR_BASE", bg = "$COLOR_BLUE", bold = true }
normal_alt = { fg = "$COLOR_BLUE", bg = "$COLOR_SURFACE0" }

select_main = { fg = "$COLOR_BASE", bg = "$COLOR_MAUVE", bold = true }
select_alt = { fg = "$COLOR_MAUVE", bg = "$COLOR_SURFACE0" }

unset_main = { fg = "$COLOR_BASE", bg = "$COLOR_RED", bold = true }
unset_alt = { fg = "$COLOR_RED", bg = "$COLOR_SURFACE0" }

[indicator]
parent = { fg = "$COLOR_SUBTEXT0", bg = "$COLOR_SURFACE0" }
current = { fg = "$COLOR_BASE", bg = "$COLOR_BLUE", bold = true }
preview = { fg = "$COLOR_MAUVE", underline = true }

padding = { open = "", close = "" }

[status]
overall = { fg = "$COLOR_TEXT", bg = "$COLOR_BASE" }

sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

perm_sep = { fg = "$COLOR_OVERLAY0" }
perm_type = { fg = "$COLOR_GREEN" }
perm_read = { fg = "$COLOR_YELLOW" }
perm_write = { fg = "$COLOR_RED" }
perm_exec = { fg = "$COLOR_TEAL" }

progress_label = { fg = "$COLOR_TEXT", bold = true }
progress_normal = { fg = "$COLOR_GREEN", bg = "$COLOR_SURFACE1" }
progress_error = { fg = "$COLOR_YELLOW", bg = "$COLOR_RED" }

[which]
border = { fg = "$COLOR_BLUE" }
mask = { bg = "$COLOR_MANTLE" }
cand = { fg = "$COLOR_TEAL" }
rest = { fg = "$COLOR_OVERLAY0" }
desc = { fg = "$COLOR_MAUVE" }
separator_style = { fg = "$COLOR_SURFACE2" }

[confirm]
border = { fg = "$COLOR_BLUE" }
title = { fg = "$COLOR_BLUE" }
body = { fg = "$COLOR_TEXT" }
list = { fg = "$COLOR_TEXT" }
btn_yes = { fg = "$COLOR_BASE", bg = "$COLOR_GREEN", bold = true }
btn_no = { fg = "$COLOR_BASE", bg = "$COLOR_RED", bold = true }

[spot]
border = { fg = "$COLOR_BLUE" }
title = { fg = "$COLOR_BLUE" }
tbl_col = { fg = "$COLOR_BLUE" }
tbl_cell = { fg = "$COLOR_YELLOW" }

[notify]
title_info = { fg = "$COLOR_GREEN" }
title_warn = { fg = "$COLOR_YELLOW" }
title_error = { fg = "$COLOR_RED" }

[pick]
border = { fg = "$COLOR_BLUE" }
active = { fg = "$COLOR_MAUVE", bold = true }
inactive = { fg = "$COLOR_TEXT" }

[input]
border = { fg = "$COLOR_BLUE" }
title = { fg = "$COLOR_TEXT" }
value = { fg = "$COLOR_TEXT" }
selected = { fg = "$COLOR_BASE", bg = "$COLOR_BLUE" }

[cmp]
border = { fg = "$COLOR_BLUE" }
active = { fg = "$COLOR_BASE", bg = "$COLOR_BLUE", bold = true }
inactive = { fg = "$COLOR_TEXT" }

[tasks]
border = { fg = "$COLOR_BLUE" }
title = { fg = "$COLOR_TEXT" }
hovered = { fg = "$COLOR_MAUVE", bold = true }

[help]
border = { fg = "$COLOR_BLUE" }
chord = { fg = "$COLOR_TEAL" }
action = { fg = "$COLOR_TEXT" }
hovered = { fg = "$COLOR_BASE", bg = "$COLOR_BLUE", bold = true }

[filetype]
rules = [
  { mime = "**/image/*", fg = "$COLOR_YELLOW" },
  { mime = "**/{audio,video}/*", fg = "$COLOR_MAUVE" },
  { mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "$COLOR_RED" },
  { mime = "**/application/{pdf,doc,rtf}", fg = "$COLOR_TEAL" },

  { url = "*", is = "orphan", bg = "$COLOR_RED" },
  { url = "*", is = "exec", fg = "$COLOR_GREEN" },

  { url = "*/", fg = "$COLOR_BLUE" },
]
EOF_TOML

  cat >"$output_dir/tmtheme.xml" <<EOF_XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Hyprdots Current</string>

  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>$COLOR_BASE</string>
        <key>foreground</key>
        <string>$COLOR_TEXT</string>
        <key>caret</key>
        <string>$COLOR_ROSEWATER</string>
        <key>selection</key>
        <string>$COLOR_SURFACE2</string>
      </dict>
    </dict>

    <dict>
      <key>name</key>
      <string>Comment</string>
      <key>scope</key>
      <string>comment</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>$COLOR_OVERLAY0</string>
        <key>fontStyle</key>
        <string>italic</string>
      </dict>
    </dict>

    <dict>
      <key>name</key>
      <string>String</string>
      <key>scope</key>
      <string>string</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>$COLOR_GREEN</string>
      </dict>
    </dict>

    <dict>
      <key>name</key>
      <string>Keyword</string>
      <key>scope</key>
      <string>keyword, storage</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>$COLOR_MAUVE</string>
      </dict>
    </dict>

    <dict>
      <key>name</key>
      <string>Number</string>
      <key>scope</key>
      <string>constant.numeric, constant.language</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>$COLOR_PEACH</string>
      </dict>
    </dict>

    <dict>
      <key>name</key>
      <string>Function</string>
      <key>scope</key>
      <string>entity.name.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>$COLOR_BLUE</string>
      </dict>
    </dict>

    <dict>
      <key>name</key>
      <string>Type</string>
      <key>scope</key>
      <string>entity.name.type, support.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>$COLOR_YELLOW</string>
      </dict>
    </dict>
  </array>
</dict>
</plist>
EOF_XML
}

render_tmux_palette() {
  local output="$1"

  cat >"$output" <<EOF_TMUX
# Generated by Hyprdots theme manager.

# Base
set -g @thm_bg "$COLOR_BASE"
set -g @thm_fg "$COLOR_TEXT"

# Colors
set -g @thm_rosewater "$COLOR_ROSEWATER"
set -g @thm_flamingo "$COLOR_FLAMINGO"
set -g @thm_pink "$COLOR_PINK"
set -g @thm_mauve "$COLOR_MAUVE"
set -g @thm_red "$COLOR_RED"
set -g @thm_maroon "$COLOR_MAROON"
set -g @thm_peach "$COLOR_PEACH"
set -g @thm_yellow "$COLOR_YELLOW"
set -g @thm_green "$COLOR_GREEN"
set -g @thm_teal "$COLOR_TEAL"
set -g @thm_sky "$COLOR_SKY"
set -g @thm_sapphire "$COLOR_SAPPHIRE"
set -g @thm_blue "$COLOR_BLUE"
set -g @thm_lavender "$COLOR_LAVENDER"

# Text
set -g @thm_subtext_1 "$COLOR_SUBTEXT1"
set -g @thm_subtext_0 "$COLOR_SUBTEXT0"

# Overlays
set -g @thm_overlay_2 "$COLOR_OVERLAY2"
set -g @thm_overlay_1 "$COLOR_OVERLAY1"
set -g @thm_overlay_0 "$COLOR_OVERLAY0"

# Surfaces
set -g @thm_surface_2 "$COLOR_SURFACE2"
set -g @thm_surface_1 "$COLOR_SURFACE1"
set -g @thm_surface_0 "$COLOR_SURFACE0"
set -g @thm_mantle "$COLOR_MANTLE"
set -g @thm_crust "$COLOR_CRUST"

# Native tmux UI
set -g status-style "bg=$COLOR_BASE,fg=$COLOR_TEXT"
set -g message-style "bg=$COLOR_SURFACE0,fg=$COLOR_TEXT"
set -g message-command-style "bg=$COLOR_SURFACE0,fg=$COLOR_TEXT"

set -g mode-style "bg=$COLOR_BLUE,fg=$COLOR_CRUST"

set -g pane-border-style "fg=$COLOR_SURFACE1"
set -g pane-active-border-style "fg=$COLOR_BLUE"

set -g @catppuccin_status_background "$COLOR_BASE"
EOF_TMUX
}

render_zellij_palette() {
  local output="$1"

  cat >"$output" <<EOF_KDL
// Generated by Hyprdots theme manager.
themes {
    current {
        bg "$COLOR_SURFACE2"
        fg "$COLOR_TEXT"
        red "$COLOR_RED"
        green "$COLOR_GREEN"
        blue "$COLOR_BLUE"
        yellow "$COLOR_YELLOW"
        magenta "$COLOR_PINK"
        orange "$COLOR_PEACH"
        cyan "$COLOR_SKY"
        black "$COLOR_MANTLE"
        white "$COLOR_TEXT"
    }
}
EOF_KDL
}

render_nvim_palette() {
  local output="$1"

  cat >"$output" <<EOF_LUA
-- Generated by Hyprdots theme manager.
-- Stage 3 will map this palette to the active Neovim colorscheme plugin.
return {
  name = "$THEME_NAME",
  display_name = "$THEME_DISPLAY_NAME",
  base = "$COLOR_BASE",
  mantle = "$COLOR_MANTLE",
  crust = "$COLOR_CRUST",
  surface0 = "$COLOR_SURFACE0",
  surface1 = "$COLOR_SURFACE1",
  surface2 = "$COLOR_SURFACE2",
  overlay0 = "$COLOR_OVERLAY0",
  overlay1 = "$COLOR_OVERLAY1",
  overlay2 = "$COLOR_OVERLAY2",
  text = "$COLOR_TEXT",
  subtext0 = "$COLOR_SUBTEXT0",
  subtext1 = "$COLOR_SUBTEXT1",
  red = "$COLOR_RED",
  green = "$COLOR_GREEN",
  yellow = "$COLOR_YELLOW",
  blue = "$COLOR_BLUE",
  mauve = "$COLOR_MAUVE",
  pink = "$COLOR_PINK",
  teal = "$COLOR_TEAL",
  sky = "$COLOR_SKY",
}
EOF_LUA
}

render_palette_env() {
  local output="$1"
  local variable_name

  {
    printf '# Generated by Hyprdots theme manager.\n'
    printf 'THEME_NAME=%q\n' "$THEME_NAME"
    printf 'THEME_DISPLAY_NAME=%q\n' "$THEME_DISPLAY_NAME"

    for variable_name in "${THEME_COLOR_VARIABLES[@]}"; do
      printf '%s=%q\n' "$variable_name" "${!variable_name}"
    done
  } >"$output"
}

render_theme_directory() {
  local output_dir="$1"

  mkdir -p -- "$output_dir"

  render_palette_env "$output_dir/palette.env"
  render_rasi_palette "$output_dir/rofi.rasi"
  cp -- "$output_dir/rofi.rasi" "$output_dir/networkmanager.rasi"
  cp -- "$output_dir/rofi.rasi" "$output_dir/bluetooth.rasi"
  render_waybar_palette "$output_dir/waybar.css"
  render_swaync_palette "$output_dir/swaync.css"
  render_wlogout_palette "$output_dir/wlogout.css"
  render_hyprlock_palette "$output_dir/hyprlock.conf"
  render_hyprland_palette "$output_dir/hyprland.lua"
  render_ghostty_palette "$output_dir/ghostty.conf"
  render_starship_palette "$output_dir/starship.toml"
  render_btop_palette "$output_dir/btop.theme"
  render_rmpc_palette "$output_dir/rmpc.ron"
  render_tmux_palette "$output_dir/tmux.conf"
  render_zellij_palette "$output_dir/zellij.kdl"
  render_yazi_flavor "$output_dir/yazi.yazi"
  render_nvim_palette "$output_dir/nvim.lua"
}

render_theme() {
  local theme_name="$1"
  local temporary_dir
  local destination
  local temporary_link

  theme_prepare_runtime
  theme_load "$theme_name"

  temporary_dir="$(mktemp -d "$THEME_CACHE_ROOT/.render.XXXXXX")"
  destination="$THEME_RENDER_ROOT/$theme_name"
  temporary_link="$THEME_CACHE_ROOT/.current.$$"

  # Invoked indirectly by the RETURN trap below.
  # shellcheck disable=SC2329
  cleanup_theme_render() {
    rm -rf -- "${temporary_dir:-}"
    rm -f -- "${temporary_link:-}"
  }

  trap cleanup_theme_render RETURN

  render_theme_directory "$temporary_dir"

  rm -rf -- "$destination"
  mv -- "$temporary_dir" "$destination"
  temporary_dir=""

  ln -s -- "rendered/$theme_name" "$temporary_link"
  mv -Tf -- "$temporary_link" "$THEME_ACTIVE_LINK"
  temporary_link=""

  trap - RETURN
}
